### PR TITLE
Fix File Extensions

### PR DESCRIPTION
**Pull request by lalls125**
change picture files from .PNG to .png to match picture links

### CODE REVIEW

**Comment by phillipsclynn** [comment]
so the ana_influence image is actually saved as ana_influence.PNG in the assets/figures folder of this repo, so this one doesn't need to be changed. It's the images in this section https://docs.iam.amr.pub/en/latest/09_technology/git.html#installing-github-desktop that aren't rendering, so if you could fix those that would be great!

**Comment by lalls125** [comment]
Hi Charly, I noticed and changed the link to .png as well.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phillipsclynn** [comment]
Hey Selina, 
Okay cool -- I don't see the commits for those images here (the only one I see is for ana_influence) so maybe you can merge them in later once you're back
Thanks!
Charly

**Comment by lalls125** [comment]
Ok I will make a note to myself to check. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
